### ISSUE TITLE
[错误报告] 

### ISSUE THREAD

**Issue by Radiation-pi** [CaaMoe/MultiLogin#103]
### BUG描述

最开始我使用了ml 0.5.4 和vc 1.19版本，一切正常
大概0.6.5出之后没多久我就更新了，vc版本也一起更新到了1.20.1 出现的情况是 littleskin玩家无法连接到服务器，报错为
Failed to verify Services signature
java.security.SignatureException: Signature length not correct: got 1 but was expecting 512

为了排除是vc的问题，我首先在单端paper中尝试安装bukkit的版本的ml 0.6.3，有一个小报错但尚且能进入游戏
更新到0.6.4后，报错同上文Failed to verify Services signature

应该是0.6.3到0.6.4版本中更新出了点什么问题，vc的版本更新我不确定是不是产生问题的原因，但是从单端看，ml更新出问题的概率是最大的，希望大佬修复!

### MultiLogin版本

0.6.3/0.6.4/0.6.5

### 系统架构

linux/win都试过

### 服务器核心

paper

### 配置文件

https://pastebin.com/F4skvu8M

### 复现步骤

1.
2.
3.
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by XiaMoHuaHuo-CN** [comment]
同样的问题：
```
[16:48:19 ERROR]: Failed to verify Services signature
java.security.SignatureException: Signature length not correct: got 1 but was expecting 512
        at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:213) ~[?:?]
        at java.security.Signature$Delegate.engineVerify(Signature.java:1435) ~[?:?]
        at java.security.Signature.verify(Signature.java:789) ~[?:?]
        at net.minecraft.util.SignatureValidator.verifySignature(SignatureValidator.java:30) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.util.SignatureValidator.lambda$from$3(SignatureValidator.java:54) ~[paper-1.20.1.jar:git-Paper-37]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at net.minecraft.util.SignatureValidator.from(SignatureValidator.java:50) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.util.SignatureValidator.validate(SignatureValidator.java:23) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.world.entity.player.ProfilePublicKey$Data.validateSignature(ProfilePublicKey.java:56) ~[?:?]
        at net.minecraft.world.entity.player.ProfilePublicKey.createValidated(ProfilePublicKey.java:28) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.network.chat.RemoteChatSession$Data.validate(RemoteChatSession.java:38) ~[?:?]        
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChatSessionUpdate(ServerGamePacketListenerImpl.java:3600) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatSessionUpdatePacket.handle(ServerboundChatSessionUpdatePacket.java:19) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.network.protocol.game.ServerboundChatSessionUpdatePacket.a(ServerboundChatSessionUpdatePacket.java:9) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-37]   
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]       
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1386) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-37]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:48:19 ERROR]: Failed to verify Services signature
java.security.SignatureException: Signature length not correct: got 1 but was expecting 512
        at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:213) ~[?:?]
        at java.security.Signature$Delegate.engineVerify(Signature.java:1435) ~[?:?]
        at java.security.Signature.verify(Signature.java:789) ~[?:?]
        at net.minecraft.util.SignatureValidator.verifySignature(SignatureValidator.java:30) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.util.SignatureValidator.lambda$from$3(SignatureValidator.java:54) ~[paper-1.20.1.jar:git-Paper-37]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at net.minecraft.util.SignatureValidator.from(SignatureValidator.java:50) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.util.SignatureValidator.validate(SignatureValidator.java:23) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.world.entity.player.ProfilePublicKey$Data.validateSignature(ProfilePublicKey.java:56) ~[?:?]
        at net.minecraft.world.entity.player.ProfilePublicKey.createValidated(ProfilePublicKey.java:28) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.network.chat.RemoteChatSession$Data.validate(RemoteChatSession.java:38) ~[?:?]        
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChatSessionUpdate(ServerGamePacketListenerImpl.java:3600) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatSessionUpdatePacket.handle(ServerboundChatSessionUpdatePacket.java:19) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.network.protocol.game.ServerboundChatSessionUpdatePacket.a(ServerboundChatSessionUpdatePacket.java:9) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-37]   
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]       
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1386) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-37]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-37]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:48:19 INFO]: XiaMoHuaHuo_CN lost connection: Invalid signature for profile public key.
Try restarting your game.
[16:48:21 INFO]: XiaMoHuaHuo_CN left the game
```

**Comment by CaaMoe** [comment]
在修了在修了，估计需要一段时间才能完成

**Comment by TaylorEevee** [comment]
同样的问题，目前客户端装no chat reports可以暂时解决

**Comment by CaaMoe** [comment]
已在最新的提交中修复了这个瘟题

**Comment by TaylorEevee** [comment]
> 已在最新的提交中修复了这个瘟题
我使用了最新的提交，然后开启时控制台提示如下然后服务端就被关闭，我是在action里下载的，这个是正常的吗
[10:06:25 ERROR] [MultiLogin]: An exception was encountered while loading the plugin.
java.lang.NoSuchFieldException: TO_SERVER
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at moe.caa.multilogin.bungee.injector.BungeeInjector.getToServerDirectionData(BungeeInjector.java:116) ~[?:?]
        at moe.caa.multilogin.bungee.injector.BungeeInjector.inject(BungeeInjector.java:35) ~[?:?]
        at fun.ksnb.multilogin.bungee.main.MultiLoginBungee.onEnable(MultiLoginBungee.java:48) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]

**Comment by XiaMoHuaHuo-CN** [comment]
> > 已在最新的提交中修复了这个瘟题
> > 我使用了最新的提交，然后开启时控制台提示如下然后服务端就被关闭，我是在action里下载的，这个是正常的吗
> > [10:06:25 ERROR] [MultiLogin]: An exception was encountered while loading the plugin.
> > java.lang.NoSuchFieldException: TO_SERVER
> > at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
> > at moe.caa.multilogin.bungee.injector.BungeeInjector.getToServerDirectionData(BungeeInjector.java:116) ~[?:?]
> > at moe.caa.multilogin.bungee.injector.BungeeInjector.inject(BungeeInjector.java:35) ~[?:?]
> > at fun.ksnb.multilogin.bungee.main.MultiLoginBungee.onEnable(MultiLoginBungee.java:48) ~[?:?]
> > at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]

或许ta修复的是Velocity上的呢

**Comment by CaaMoe** [comment]
> > 已在最新的提交中修复了这个瘟题
> > 我使用了最新的提交，然后开启时控制台提示如下然后服务端就被关闭，我是在action里下载的，这个是正常的吗
> > [10:06:25 ERROR] [MultiLogin]: An exception was encountered while loading the plugin.
> > java.lang.NoSuchFieldException: TO_SERVER
> > at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
> > at moe.caa.multilogin.bungee.injector.BungeeInjector.getToServerDirectionData(BungeeInjector.java:116) ~[?:?]
> > at moe.caa.multilogin.bungee.injector.BungeeInjector.inject(BungeeInjector.java:35) ~[?:?]
> > at fun.ksnb.multilogin.bungee.main.MultiLoginBungee.onEnable(MultiLoginBungee.java:48) ~[?:?]
> > at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]

请更新一下你的Bungeecord

**Comment by TaylorEevee** [comment]
> > > 已在最新的提交中修复了这个瘟题
> > > 我使用了最新的提交，然后开启时控制台提示如下然后服务端就被关闭，我是在action里下载的，这个是正常的吗
> > > [10:06:25 ERROR] [MultiLogin]: An exception was encountered while loading the plugin.
> > > java.lang.NoSuchFieldException: TO_SERVER
> > > at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
> > > at moe.caa.multilogin.bungee.injector.BungeeInjector.getToServerDirectionData(BungeeInjector.java:116) ~[?:?]
> > > at moe.caa.multilogin.bungee.injector.BungeeInjector.inject(BungeeInjector.java:35) ~[?:?]
> > > at fun.ksnb.multilogin.bungee.main.MultiLoginBungee.onEnable(MultiLoginBungee.java:48) ~[?:?]
> > > at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > > at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > > at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > > at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> 
> 或许ta修复的是Velocity上的呢

emmm?，可是我现在是加载最新的直接起不来

**Comment by CaaMoe** [comment]
> > > > 已在最新的提交中修复了这个瘟题
> > > > 我使用了最新的提交，然后开启时控制台提示如下然后服务端就被关闭，我是在action里下载的，这个是正常的吗
> > > > [10:06:25 ERROR] [MultiLogin]: An exception was encountered while loading the plugin.
> > > > java.lang.NoSuchFieldException: TO_SERVER
> > > > at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
> > > > at moe.caa.multilogin.bungee.injector.BungeeInjector.getToServerDirectionData(BungeeInjector.java:116) ~[?:?]
> > > > at moe.caa.multilogin.bungee.injector.BungeeInjector.inject(BungeeInjector.java:35) ~[?:?]
> > > > at fun.ksnb.multilogin.bungee.main.MultiLoginBungee.onEnable(MultiLoginBungee.java:48) ~[?:?]
> > > > at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > > > at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > > > at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > > > at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > 
> > 
> > 或许ta修复的是Velocity上的呢
> 
> emmm?，可是我现在是加载最新的直接起不来

请坐和放宽，Bungee实现有点问题，正在修复。

目前的反签名逻辑是拦截PlayerSessionUpdate来实现的，你可以在Bukkit上依赖ProtocolLib弄个小插件来阻止这个包的接收

**Comment by CaaMoe** [comment]
> > > > 已在最新的提交中修复了这个瘟题
> > > > 我使用了最新的提交，然后开启时控制台提示如下然后服务端就被关闭，我是在action里下载的，这个是正常的吗
> > > > [10:06:25 ERROR] [MultiLogin]: An exception was encountered while loading the plugin.
> > > > java.lang.NoSuchFieldException: TO_SERVER
> > > > at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
> > > > at moe.caa.multilogin.bungee.injector.BungeeInjector.getToServerDirectionData(BungeeInjector.java:116) ~[?:?]
> > > > at moe.caa.multilogin.bungee.injector.BungeeInjector.inject(BungeeInjector.java:35) ~[?:?]
> > > > at fun.ksnb.multilogin.bungee.main.MultiLoginBungee.onEnable(MultiLoginBungee.java:48) ~[?:?]
> > > > at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > > > at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > > > at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > > > at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
> > 
> > 
> > 或许ta修复的是Velocity上的呢
> 
> emmm?，可是我现在是加载最新的直接起不来

已在最新的提交中修复了这个问题，再试一下吧
