### ISSUE TITLE
[错误报告] 无法读取littleskin.yml

### ISSUE THREAD

**Issue by orbitgw** [CaaMoe/MultiLogin#105]
### BUG描述

装了此插件，配置好后启动报错.权限rw-rw-r--
```bash
moe.caa.multilogin.core.configuration.ConfException: Unable to read authentication service config under file plugins/MultiLogin/services/littleskin.yml
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:113) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:108) ~[?:?]
        at moe.caa.multilogin.core.main.MultiCore.load(MultiCore.java:117) ~[?:?]
        at moe.caa.multilogin.bukkit.main.MultiLoginBukkit.onEnable(MultiLoginBukkit.java:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: moe.caa.multilogin.core.configuration.ConfException: Yggdrasil id 888 is out of bounds, The value can only be between 0 and 127.
        at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.checkValid(BaseServiceConfig.java:32) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.<init>(BaseServiceConfig.java:27) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.yggdrasil.BaseYggdrasilServiceConfig.<init>(BaseYggdrasilServiceConfig.java:24) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.yggdrasil.BlessingSkinYggdrasilServiceConfig.<init>(BlessingSkinYggdrasilServiceConfig.java:15) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.readServiceConfig(PluginConfig.java:211) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:111) ~[?:?]
        ... 17 more
[14:15:16] [Server thread/ERROR]: [MultiLogin] null
moe.caa.multilogin.core.configuration.ConfException: Unable to read authentication service config under file plugins/MultiLogin/services/offical.yml
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:113) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:108) ~[?:?]
        at moe.caa.multilogin.core.main.MultiCore.load(MultiCore.java:117) ~[?:?]
        at moe.caa.multilogin.bukkit.main.MultiLoginBukkit.onEnable(MultiLoginBukkit.java:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: moe.caa.multilogin.core.configuration.ConfException: Yggdrasil id 666 is out of bounds, The value can only be between 0 and 127.
        at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.checkValid(BaseServiceConfig.java:32) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.<init>(BaseServiceConfig.java:27) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.yggdrasil.BaseYggdrasilServiceConfig.<init>(BaseYggdrasilServiceConfig.java:24) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.yggdrasil.OfficialYggdrasilServiceConfig.<init>(OfficialYggdrasilServiceConfig.java:13) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.readServiceConfig(PluginConfig.java:202) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:111) ~[?:?]
        ... 17 more
```

### MultiLogin版本

v0.6.5

### 系统架构

linux/amd64

### 服务器核心

spigot

### 配置文件

https://pastebin.mozilla.org/R5MOk9DV

### 复现步骤

1.
2.
3.
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by orbitgw** [comment]
配置文件：
```yaml
# Below, only the most basic configuration is provided.
# You can refer to the template file to complete all configurations.

# Please edit before use.
id: 888

name: 'Little Skin'
# Don't change it unless you really want to.
serviceType: BLESSING_SKIN
yggdrasilAuth:
  blessingSkin:
    apiRoot: 'https://littleskin.cn/api/yggdrasil'
```

**Comment by Becods** [comment]
```
Yggdrasil id 888 is out of bounds, The value can only be between 0 and 127.
```
id可用范围为`0-127`
