### ISSUE TITLE
[错误报告] class java.lang.String cannot be cast to class com.mojang.authlib.GameProfile

### ISSUE THREAD

**Issue by mwx2006** [CaaMoe/MultiLogin#115]
### BUG描述

[23:04:16 INFO]: Disconnecting MWX_darkrain (/xxx.xxx.xxx.xxx:xxx): Failed to verify username!
[23:04:16 WARN]: Exception verifying MWX_darkrain
java.lang.ClassCastException: class java.lang.String cannot be cast to class com.mojang.authlib.GameProfile (java.lang.String is in module java.base of loader 'bootstrap'; com.mojang.authlib.GameProfile is in unnamed module of loader java.net.URLClassLoader @1ed6993a)
        at moe.caa.multilogin.bukkit.injector.proxy.YggdrasilMinecraftSessionServiceInvocationHandler.invoke(YggdrasilMinecraftSessionServiceInvocationHandler.kt:23) ~[?:?]
        at jdk.proxy2.$Proxy115.hasJoinedServer(Unknown Source) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$2.run(ServerLoginPacketListenerImpl.java:286) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:04:16 INFO]: MWX_darkrain (/xxx.xxx.xxx.xxx:xxx) lost connection: Failed to verify username!

### MultiLogin版本

v0.6.6

### 系统架构

linux/amd64

### 服务器核心

purpur 1.20.2

### 配置文件

-

### 复现步骤

1.Java登录必现
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
已在 [此次](https://github.com/CaaMoe/MultiLogin/commit/41e7d41f485f913a43b103fa115071c61ffeb430) 提交中修复这个问题，感谢反馈
