### ISSUE TITLE
Exception:无法读取文件plugins\MultiLogin\services\ official .yml下的认证服务配置

### ISSUE THREAD

**Issue by 45610465** [CaaMoe/MultiLogin#122]
17:43:44 [严重] [MultiLogin] null
moe.caa.multilogin.core.configuration.ConfException: Unable to read authentication service config under file plugins\MultiLogin\services\template_cn_full.yml
    at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:113)
    at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
    at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
    at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
    at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:108)
    at moe.caa.multilogin.core.main.MultiCore.load(MultiCore.java:117)
    at fun.ksnb.multilogin.bungee.main.MultiLoginBungee.onEnable(MultiLoginBungee.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:266)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: moe.caa.multilogin.core.configuration.ConfException: Yggdrasil id -1 is out of bounds, The value can only be between 0 and 127.
    at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.checkValid(BaseServiceConfig.java:32)
    at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.<init>(BaseServiceConfig.java:27)
    at moe.caa.multilogin.core.configuration.service.yggdrasil.BaseYggdrasilServiceConfig.<init>(BaseYggdrasilServiceConfig.java:24)
    at moe.caa.multilogin.core.configuration.service.yggdrasil.BlessingSkinYggdrasilServiceConfig.<init>(BlessingSkinYggdrasilServiceConfig.java:15)
    at moe.caa.multilogin.core.configuration.PluginConfig.readServiceConfig(PluginConfig.java:211)
    at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:111)
    ... 10 more

使用的最新版本的BC

**Comment by Becods** [comment]
```
Yggdrasil id -1 is out of bounds, The value can only be between 0 and 127.
```
template_cn_full.yml中Yggdrasil的值只能为0-127
