### ISSUE TITLE
基岩版加入游戏出现严重报错，java正常

### ISSUE THREAD

**Issue by 45610465** [CaaMoe/MultiLogin#123]
16:49:28 [严重] java.util.concurrent.CompletionException: java.lang.LinkageError: loader constraint violation: loader moe.caa.multilogin.loader.classloader.PriorAllURLClassLoader @45bf6f39 wants to load class org.geysermc.floodgate.util.BedrockData. A different class with the same name was previously loaded by net.md_5.bungee.api.plugin.PluginClassloader @e044b4a. (org.geysermc.floodgate.util.BedrockData is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @e044b4a, parent loader 'app')

16:49:28 [严重]     at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)

16:49:28 [严重]     at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)

16:49:28 [严重]     at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936)

16:49:28 [严重]     at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)

16:49:28 [严重]     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)

16:49:28 [严重]     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)

16:49:28 [严重]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

16:49:28 [严重]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

16:49:28 [严重]     at java.base/java.lang.Thread.run(Thread.java:833)

16:49:28 [严重] Caused by: java.lang.LinkageError: loader constraint violation: loader moe.caa.multilogin.loader.classloader.PriorAllURLClassLoader @45bf6f39 wants to load class org.geysermc.floodgate.util.BedrockData. A different class with the same name was previously loaded by net.md_5.bungee.api.plugin.PluginClassloader @e044b4a. (org.geysermc.floodgate.util.BedrockData is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @e044b4a, parent loader 'app')

16:49:28 [严重]     at moe.caa.multilogin.core.auth.service.floodgate.FloodgateAuthenticationService.handle(FloodgateAuthenticationService.java:36)

16:49:28 [严重]     at org.geysermc.floodgate.addon.data.HandshakeHandlersImpl.callHandshakeHandlers(HandshakeHandlersImpl.java:74)

16:49:28 [严重]     at org.geysermc.floodgate.player.FloodgateHandshakeHandler.handlePart2(FloodgateHandshakeHandler.java:227)

16:49:28 [严重]     at org.geysermc.floodgate.player.FloodgateHandshakeHandler.lambda$handle$1(FloodgateHandshakeHandler.java:184)

16:49:28 [严重]     at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)

16:49:28 [严重]     ... 6 more

16:49:55 [信息] [Geyser-BungeeCord] menghui12285 因为 Read timed out. 与 Java 版服务器 断开了连接
16:49:55 [严重] io.netty.handler.timeout.ReadTimeoutException

**Comment by CaaMoe** [comment]
在bungee下geyser和floodgate装在一起会出现问题，使用 standalone 模式就好了
