### ISSUE TITLE
[错误报告] Velocity在3.3.0更改了ServerLogin的类名

### ISSUE THREAD

**Issue by heartalborada-del** [CaaMoe/MultiLogin#133]
### BUG描述

如题，在Velocity-3.3.0-SNAPSHOT-338和339版本测试v0.6.7和最新构建均出现如下报错
```
[multilogin]: An exception was encountered while loading the plugin.
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at moe.caa.multilogin.loader.main.PluginLoader.findClass(PluginLoader.java:197) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.MultiLoginVelocity.onInitialize(MultiLoginVelocity.java:59) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.Lmbda$10.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-283005c8-b337)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-283005c8-b337)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-283005c8-b337)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.ServerLogin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at moe.caa.multilogin.loader.classloader.PriorURLClassLoader.loadClass(PriorURLClassLoader.java:43) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 11 more
```
最新的类名似乎从`ServerLogin`，更改为了`ServerLoginPacket`  ~~希望能尽快修复~~

### MultiLogin版本

v0.6.7

### 系统架构

linux/amd64

### 服务器核心

velocity

### 配置文件

https://pastebin.mozilla.org/zPqPwfGA

### 日志

https://pastebin.mozilla.org/NjN91Oe4

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by half-nothing** [comment]
同样的问题，不过这次出错的类变成了EncryptionResponse
```
[14:19:42 ERROR] [multilogin]: An exception was encountered while loading the plugin.
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/EncryptionResponse
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at moe.caa.multilogin.loader.main.PluginLoader.findClass(PluginLoader.java:197) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.MultiLoginVelocity.onInitialize(MultiLoginVelocity.java:59) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.Lmbda$21.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-335.jar:3.3.0-SNAPSHOT (git-953ab6d8-b335)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-335.jar:3.3.0-SNAPSHOT (git-953ab6d8-b335)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-335.jar:3.3.0-SNAPSHOT (git-953ab6d8-b335)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.EncryptionResponse
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at moe.caa.multilogin.loader.classloader.PriorURLClassLoader.loadClass(PriorURLClassLoader.java:43) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 11 more
```

**Comment by half-nothing** [comment]
> ### BUG描述
> 如题，在Velocity-3.3.0-SNAPSHOT-338和339版本测试v0.6.7和最新构建均出现如下报错
> 
> ```
> [multilogin]: An exception was encountered while loading the plugin.
> java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin
>         at java.lang.Class.forName0(Native Method) ~[?:?]
>         at java.lang.Class.forName(Class.java:467) ~[?:?]
>         at moe.caa.multilogin.loader.main.PluginLoader.findClass(PluginLoader.java:197) ~[?:?]
>         at fun.ksnb.multilogin.velocity.main.MultiLoginVelocity.onInitialize(MultiLoginVelocity.java:59) ~[?:?]
>         at fun.ksnb.multilogin.velocity.main.Lmbda$10.execute(Unknown Source) ~[?:?]
>         at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-283005c8-b337)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-283005c8-b337)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-283005c8-b337)]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>         at java.lang.Thread.run(Thread.java:840) [?:?]
> Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.ServerLogin
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
>         at moe.caa.multilogin.loader.classloader.PriorURLClassLoader.loadClass(PriorURLClassLoader.java:43) ~[?:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
>         ... 11 more
> ```
> 
> 最新的类名似乎从`ServerLogin`，更改为了`ServerLoginPacket` ~希望能尽快修复~
> 
> ### MultiLogin版本
> v0.6.7
> 
> ### 系统架构
> linux/amd64
> 
> ### 服务器核心
> velocity
> 
> ### 配置文件
> https://pastebin.mozilla.org/zPqPwfGA
> 
> ### 日志
> https://pastebin.mozilla.org/NjN91Oe4
> 
> ### 复现步骤
> _No response_
> 
> ### 确认一遍
> * [x]  我已完成且认真地填写完了报告所需要的信息
> * [x]  我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

你可以暂时使用[这个版本](https://github.com/half-nothing/MultiLogin/releases)
