### ISSUE TITLE
BungeeCord服务端无法显示皮肤。

### ISSUE THREAD

**Issue by 090424xsp** [CaaMoe/MultiLogin#149]
### BUG描述

无法在服务器内显示皮肤，并在加入服务器时报错。
我尝试了回收档案。
正式版也无法显示皮肤，且报错相同

### MultiLogin版本

MultiLogin-Bungee-Build_d35fba5

### 系统架构

Windows 10 10.0 (amd64)

### 服务器核心

BungeeCord

### 配置文件

皮肤站的配置：https://pastebin.mozilla.org/tim9u7tp                       插件的配置文件：https://pastebin.mozilla.org/8XJggmiw

### 日志

https://pastebin.mozilla.org/Yi8Or8rQ

### 复现步骤

1.把插件放入plugins文件夹
2.启动
3.使用皮肤站登录
4.报错

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [x] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
链接404了，重新提交一下吧

**Comment by 090424xsp** [comment]
服务器的：https://pastebin.mozilla.org/Uo508ZcL

**Comment by 090424xsp** [comment]
服务器的：https://pastebin.mozilla.org/Uo508ZcL   插件的：https://pastebin.mozilla.org/xbbgQ79d      配置皮肤站的：https://pastebin.mozilla.org/did05ToR

**Comment by 090424xsp** [comment]
> 服务器的：https://pastebin.mozilla.org/Uo508ZcL 插件的：https://pastebin.mozilla.org/xbbgQ79d 配置皮肤站的：https://pastebin.mozilla.org/did05ToR
服务器的发错了  应该是：https://pastebin.mozilla.org/95Yd5Yw6

**Comment by 090424xsp** [comment]
服务器的：https://pastebin.mozilla.org/95Yd5Yw6 插件的：https://pastebin.mozilla.org/xbbgQ79d 配置皮肤站的：https://pastebin.mozilla.org/did05ToR

**Comment by CaaMoe** [comment]
在对应皮肤站上的对应角色有皮肤吗

**Comment by 090424xsp** [comment]
有

**Comment by 090424xsp** [comment]
![image](https://github.com/CaaMoe/MultiLogin/assets/163093337/a1baf560-d337-4b5d-bee6-00cb55a1d948)

**Comment by CaaMoe** [comment]
在multilogin/config.yml中开启debug模式再采集一些更详细的日志出来吧

**Comment by 090424xsp** [comment]
好

**Comment by 090424xsp** [comment]
开了DEBUG以后的日志文件:https://pastebin.mozilla.org/tFFws0uH

**Comment by CaaMoe** [comment]
请检查皮肤站程序是否运行正常，仅使用authlib-injector能不能正常显示皮肤

**Comment by 090424xsp** [comment]
使用authlib-injector会无法加入服务器，提示“无效的个人信息公钥签名  请尝试重启游戏”

**Comment by 090424xsp** [comment]
我好像发现了一些问题：它获取到了我的内网地址{skin}  而skin对应的并不是皮肤站，而是我的官网    正确的应该是skin:100我有办法修改这个ip吗

**Comment by 090424xsp** [comment]
把skin改为skin:100应该可以访问皮肤文件

**Comment by 090424xsp** [comment]
我成功的更改了内网端口 可报错持续  内容似乎不一样了:                                                                                          [18:40:59 INFO]: [/183.217.89.159:14231] <-> InitialHandler has connected
[18:40:59 INFO] [MultiLogin]: [DEBUG] 090424's hasJoined verification order: [2], [3, 5]
[18:40:59 INFO] [MultiLogin]: [DEBUG] --> GET http://skins.clearcraft.cn/api/yggdrasil/sessionserver/session/minecraft/hasJoined?username=090424&serverId=-336ea7ec4e11b2fff0fd328124f73dcdc48c9657
[18:41:00 INFO] [MultiLogin]: [DEBUG] <-- 200 http://skins.clearcraft.cn/api/yggdrasil/sessionserver/session/minecraft/hasJoined?username=090424&serverId=-336ea7ec4e11b2fff0fd328124f73dcdc48c9657 (483ms)
[18:41:00 INFO] [MultiLogin]: [DEBUG] <-- (1927 bytes)
[18:41:00 INFO] [MultiLogin]: 090424(uuid: ef4948ac-6fc3-36a4-8f4f-37fe2ab6535a) from authentication service ClearCraft(yid: 2) has been authenticated, profile redirected to 090424(uuid: ef4948ac-6fc3-36a4-8f4f-37fe2ab6535a).
[18:41:00 INFO] [MultiLogin]: [DEBUG] Skin restore result of 090424 is RESTORER_ASYNC.
[18:41:00 INFO] [MultiLogin]: [DEBUG] --> GET http://skin/textures/fb7f6e7409000d907a68a762db9a88fe824daebeaf4b40a9d0c7fda5b0bc5e79
[18:41:00 INFO]: [090424|/183.217.89.159:14231] <-> ServerConnector [大厅] has connected
[18:41:01 INFO] [MultiLogin]: [DEBUG] <-- 200 http://skin/textures/fb7f6e7409000d907a68a762db9a88fe824daebeaf4b40a9d0c7fda5b0bc5e79 (1474ms)
[18:41:01 INFO] [MultiLogin]: [DEBUG] <-- (3543 bytes)
[18:41:01 INFO] [MultiLogin]: [DEBUG] --> POST https://api.mineskin.org/generate/url
[18:41:01 INFO] [MultiLogin]: [DEBUG] --> (160 bytes)
[18:41:03 INFO] [MultiLogin]: [DEBUG] <-- 400 https://api.mineskin.org/generate/url (1366ms)
[18:41:03 INFO] [MultiLogin]: [DEBUG] <-- (187 bytes)
[18:41:03 ERROR] [MultiLogin]: An exception occurred while processing the skin repair.
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonObject(String)" because the return value of "com.google.gson.JsonObject.getAsJsonObject(String)" is null
        at moe.caa.multilogin.core.skinrestorer.SkinRestorerFlows.call(SkinRestorerFlows.java:86) ~[?:?]
        at moe.caa.multilogin.core.skinrestorer.SkinRestorerCore.lambda$doRestorer$0(SkinRestorerCore.java:155) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]                                                                                                                              以上是我登录时的所有日志（从登录开始）

**Comment by CaaMoe** [comment]
修复模式请改成UPLOAD

**Comment by 090424xsp** [comment]
谢谢您  皮肤已经可以正常显示了
