### ISSUE TITLE
[错误报告] 服务器尚未添加任何世界树验证服务器，请尝试与服务器管理员取得联系

### ISSUE THREAD

**Issue by yangyinxiao6** [CaaMoe/MultiLogin#152]
### BUG描述

使用littleskin加入服务器提示:服务器尚未添加任何世界树验证服务器，请尝试与服务器管理员取得联系
因为服务器封海外了，所以迫不得已才使用了multilogin，但是无法使用littleskin登录
![QQ截图20240329165720](https://github.com/CaaMoe/MultiLogin/assets/112427318/8cfb0691-5520-4606-b0ff-007b410b0f51)

### MultiLogin版本

MultiLogin v0.6.7 on Velocity - 3.3.0-SNAPSHOT

### 系统架构

Windows/amd64

### 服务器核心

Velocity

### 配置文件

https://mclo.gs/UzYEUZs

### 日志

https://mclo.gs/a3YvJ4v

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by yangyinxiao6** [comment]
![QQ截图20240329171928](https://github.com/CaaMoe/MultiLogin/assets/112427318/8a9de215-f636-45e9-82cd-fcb348cba55d)
x现在正版也进不去了

**Comment by Becods** [comment]
<pre><code>moe.caa.multilogin.core.configuration.ConfException: Unable to read authentication service config under file plugins\multilogin\services\littleskin.yml
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:113) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:108) ~[?:?]
        at moe.caa.multilogin.core.main.MultiCore.reload(MultiCore.java:147) ~[?:?]
        at moe.caa.multilogin.core.command.commands.RootCommand.executeReload(RootCommand.java:173) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:141) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at moe.caa.multilogin.core.command.CommandHandler.lambda$execute$0(CommandHandler.java:59) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:[30](https://mclo.gs/a3YvJ4v#L30)4) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: moe.caa.multilogin.core.configuration.ConfException: <strong>Yggdrasil id -1 is out of bounds, The value can only be between 0 and 127.</strong>
        at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.checkValid(BaseServiceConfig.java:[32](https://mclo.gs/a3YvJ4v#L32)) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.<init>(BaseServiceConfig.java:27) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.yggdrasil.BaseYggdrasilServiceConfig.<init>(BaseYggdrasilServiceConfig.java:24) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.yggdrasil.BlessingSkinYggdrasilServiceConfig.<init>(BlessingSkinYggdrasilServiceConfig.java:15) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.readServiceConfig(PluginConfig.java:211) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:111) ~[?:?]
        ... 16 more
</code></pre>
将id设置为-1以外的值

**Comment by yangyinxiao6** [comment]
设置成-1以外的数值之后会导致服务端崩溃
日志：https://mclo.gs/zsaap8T

**Comment by Becods** [comment]
<pre><code>
[06:55:21 ERROR] [multilogin]: null
moe.caa.multilogin.core.configuration.ConfException: Unable to read authentication service config under file plugins\multilogin\services\floodgate.yml
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:113) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:108) ~[?:?]
        at moe.caa.multilogin.core.main.MultiCore.load(MultiCore.java:117) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.MultiLoginVelocity.onInitialize(MultiLoginVelocity.java:58) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.Lmbda$8.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: moe.caa.multilogin.core.configuration.ConfException: <b>Yggdrasil id -1 is out of bounds, The value can only be between 0 and 127.</b>
        at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.checkValid(BaseServiceConfig.java:32) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.<init>(BaseServiceConfig.java:27) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.FloodgateServiceConfig.<init>(FloodgateServiceConfig.java:9) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.readServiceConfig(PluginConfig.java:228) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:111) ~[?:?]
        ... 13 more
[06:55:21 ERROR] [multilogin]: null
moe.caa.multilogin.core.configuration.ConfException: Unable to read authentication service config under file plugins\multilogin\services\template_cn_full.yml
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:113) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:108) ~[?:?]
        at moe.caa.multilogin.core.main.MultiCore.load(MultiCore.java:117) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.MultiLoginVelocity.onInitialize(MultiLoginVelocity.java:58) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.Lmbda$8.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: moe.caa.multilogin.core.configuration.ConfException: <b>Yggdrasil id -1 is out of bounds, The value can only be between 0 and 127.</b>
        at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.checkValid(BaseServiceConfig.java:32) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.BaseServiceConfig.<init>(BaseServiceConfig.java:27) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.yggdrasil.BaseYggdrasilServiceConfig.<init>(BaseYggdrasilServiceConfig.java:24) ~[?:?]
        at moe.caa.multilogin.core.configuration.service.yggdrasil.OfficialYggdrasilServiceConfig.<init>(OfficialYggdrasilServiceConfig.java:13) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.readServiceConfig(PluginConfig.java:202) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:111) ~[?:?]
        ... 13 more
[06:55:21 ERROR] [multilogin]: An exception was encountered while loading the plugin.
moe.caa.multilogin.core.configuration.ConfException: The same authentication service id value 30 exists.
        at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:130) ~[?:?]
        at moe.caa.multilogin.core.main.MultiCore.load(MultiCore.java:117) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.MultiLoginVelocity.onInitialize(MultiLoginVelocity.java:58) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.Lmbda$8.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
</code></pre>
将id设置为-1以外的值
