### ISSUE TITLE
[错误报告] paper1.20.2 基岩版加入错误

### ISSUE THREAD

**Issue by 666sxrA** [CaaMoe/MultiLogin#173]
### BUG描述

paper1.20.2 基岩版加入错误 使用独立模式或者Geyser Floodgate装一起都是这个报错

[16:57:30 INFO]: [Vault] No new version available
[16:57:52 INFO]: [MultiLogin] BoweryBlock9958(uuid: 00000000-0000-0000-0009-01fdd028adff) from authentication service Bedrock(yid: 2) has been authenticated, profile redirected to BE_BoweryBlock9958(uuid: 00000000-0000-0000-0009-01fdd028adff).
[16:57:53 INFO]: UUID of player BE_BoweryBlock9958 is 00000000-0000-0000-0009-01fdd028adff
[16:57:53 INFO]: [floodgate] Floodgate 玩家 BE_BoweryBlock9958 加入了 (UUID: 00000000-0000-0000-0009-01fdd028adff)
[16:57:53 INFO]: BE_BoweryBlock9958 joined the game
[16:57:53 INFO]: BE_BoweryBlock9958[/118.213.158.124:55578] logged in with entity id 179 at ([world]0.8088094, 254.0, -3.8123274)
[16:57:53 ERROR]: Packet encoding of packet ClientboundPlayerInfoUpdatePacket (ID: 60) threw (skippable? false)
io.netty.handler.codec.EncoderException: String too big (was 18 characters, max 16)
        at net.minecraft.network.Utf8String.write(Utf8String.java:35) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.network.FriendlyByteBuf.writeUtf(FriendlyByteBuf.java:686) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket$Action.lambda$static$1(ClientboundPlayerInfoUpdatePacket.java:127) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket.lambda$write$1(ClientboundPlayerInfoUpdatePacket.java:92) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.network.FriendlyByteBuf.writeCollection(FriendlyByteBuf.java:226) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket.write(ClientboundPlayerInfoUpdatePacket.java:88) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:42) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.20.2.jar:git-Paper-318]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.lumine.mythic.core.volatilecode.v1_20_R2.packets.VolatileChannelHandler.write(VolatileChannelHandler.java:76) ~[MythicMobs-5.6.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:57:54 INFO]: [floodgate] Floodgate 玩家 BE_BoweryBlock9958 已断开连接
[16:57:54 INFO]: BE_BoweryBlock9958 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: String too big (was 18 characters, max 16)
[16:57:54 INFO]: [voicechat] Disconnecting client BE_BoweryBlock9958
[16:57:54 INFO]: BE_BoweryBlock9958 left the game

### MultiLogin版本

1.20.2

### 系统架构

windows/amd64

### 服务器核心

spigot

### 配置文件

https://pastebin.mozilla.org/yyqzvjRn

### 复现步骤

1.paper1.21.2
2.装上Geyser Floodgate MultiLogin
3.用默认配置
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
名字太长了

**Comment by 666sxrA** [comment]
这个问题会导致java版已登录客户端弹相同的错误

**Comment by CaaMoe** [comment]
名字太长了

**Comment by Becods** [comment]
名称太长
[MC-2555](https://bugs.mojang.com/browse/MC-2555)
```
Packet encoding of packet ClientboundPlayerInfoUpdatePacket (ID: 60) threw (skippable? false)
io.netty.handler.codec.EncoderException: String too big (was 18 characters, max 16)
```
