### ISSUE TITLE
velocity每次登录后台都会报错

### ISSUE THREAD

**Issue by Kamijouko** [CaaMoe/MultiLogin#27]
velocity：3.1.1
velocity用的Hotspot构建的JDK11
MineCraft版本：1.12.2
用了官方服务器和sponge测试，不论是微软登入还是Yggdrasil，客户端连接后均会报以下错误：（从插件log里截的）
```
[2021-12-15 - 21:31:07] [Netty NIO Worker #10 - ERROR]: Exception during assignment.
java.lang.ClassCastException: Cannot cast com.velocitypowered.proxy.connection.client.LoginInboundConnection to com.velocitypowered.proxy.connection.client.InitialInboundConnection
	at java.lang.Class.cast(Class.java:3889) ~[?:?]
	at fun.ksnb.multilogin.velocity.auth.MultiLoginEncryptionResponse.getValues(MultiLoginEncryptionResponse.java:120) [MultiLogin-2374552369195948043-MultiLogin-Velocity.JarFile.jar:?]
	at fun.ksnb.multilogin.velocity.auth.MultiLoginEncryptionResponse.handle(MultiLoginEncryptionResponse.java:69) [MultiLogin-2374552369195948043-MultiLogin-Velocity.JarFile.jar:?]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:142) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) [velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [velocity.jar:3.1.1]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [velocity.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [velocity.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [velocity.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [velocity.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [velocity.jar:3.1.1]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [velocity.jar:3.1.1]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [velocity.jar:3.1.1]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [velocity.jar:3.1.1]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [velocity.jar:3.1.1]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [velocity.jar:3.1.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [velocity.jar:3.1.1]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [velocity.jar:3.1.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [velocity.jar:3.1.1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

以及
```
[2021-12-15 - 21:29:08] [Netty NIO Worker #3 - ERROR]: Exception during assignment.
java.lang.ClassCastException: Cannot cast com.velocitypowered.proxy.connection.client.LoginInboundConnection to com.velocitypowered.proxy.connection.client.InitialInboundConnection
	at java.lang.Class.cast(Class.java:3889) ~[?:?]
	at fun.ksnb.multilogin.velocity.auth.MultiLoginEncryptionResponse.getValues(MultiLoginEncryptionResponse.java:120) [MultiLogin-2374552369195948043-MultiLogin-Velocity.JarFile.jar:?]
	at fun.ksnb.multilogin.velocity.auth.MultiLoginEncryptionResponse.handle(MultiLoginEncryptionResponse.java:69) [MultiLogin-2374552369195948043-MultiLogin-Velocity.JarFile.jar:?]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:142) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) [velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [velocity.jar:3.1.1]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [velocity.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [velocity.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [velocity.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [velocity.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [velocity.jar:3.1.1]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [velocity.jar:3.1.1]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [velocity.jar:3.1.1]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [velocity.jar:3.1.1]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [velocity.jar:3.1.1]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [velocity.jar:3.1.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [velocity.jar:3.1.1]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [velocity.jar:3.1.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [velocity.jar:3.1.1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
补充：velocity把ip转发换成None试过但是没有改善
在这个报错之后会出现验证账号的log是可以正常登陆的，只是相同id的情况下不会出现拒绝登录提示，而是会登陆超时

**Comment by Kamijouko** [comment]
还附加一个BungeeCord的全局白名单不起作用，即使每个节点都设置whitelist: false 全局whitelist也是false，进入服务器依旧会提示没有白名单权限0W0

**Comment by CaaMoe** [comment]
已修复，感谢反馈
