### ISSUE TITLE
希望兼容Java11

### ISSUE THREAD

**Issue by BecodReyes** [CaaMoe/MultiLogin#3]
服务端版本: paper-1.16.4-391
服务器架构: x86_64
服务器系统: Centos 7.8.2003
Java版本: OpenJDK 11.0.9.1

已测试在Java8中运行良好
BASE64Decoder已在Java9及更高版本中被移除，希望作者能够兼容一下Java11

log:
```
[08:38:55 INFO]: [MultiLogin] Enabling MultiLogin v1.0-BETA.11*
[08:38:55 ERROR]: Error occurred while enabling MultiLogin v1.0-BETA.11 (Is it up to date?)
java.lang.NoClassDefFoundError: sun/misc/BASE64Decoder
	at moe.caa.multilogin.core.MultiCore.<clinit>(MultiCore.java:23) ~[?:?]
	at moe.caa.multilogin.bukkit.MultiLogin.onEnable(MultiLogin.java:25) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-391]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-391]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-391]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-391]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Decoder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Paper-391]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 12 more
[08:38:55 INFO]: [MultiLogin] Disabling MultiLogin v1.0-BETA.11
[08:38:55 ERROR]: Error occurred while disabling MultiLogin v1.0-BETA.11 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class moe.caa.multilogin.core.MultiCore
	at moe.caa.multilogin.bukkit.MultiLogin.onDisable(MultiLogin.java:60) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-391]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-391]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-391]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-391]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by CaaMoe** [comment]
你好，将在下一版本删除对BASE64Decoder类的使用。请耐心等待。

**Comment by CaaMoe** [comment]
新版本MultiLogin（v1.0-BETA.12）已兼容Java11环境，感谢反馈问题。
