### ISSUE TITLE
[建议] 请问可否增加对BC的fork版本HexagonMC 增加支持

### ISSUE THREAD

**Issue by xiamo070091** [CaaMoe/MultiLogin#37]
### 描述功能请求

现版本无法支持[HexagonMC](https://github.com/HexagonMC/BungeeCord)，会在启动时显示出现错，然后关服
```18:44:02 [INFO] [MultiLogin] 加载文件: config.yml
18:44:03 [INFO] [MultiLogin] 添加 Yggdrasil 账户验证服务器 Demo Yggdrasil(demo), 但未启用它。
18:44:03 [INFO] [MultiLogin] 添加 Yggdrasil 账户验证服务器 正版(official)。
18:44:03 [INFO] [MultiLogin] 成功连接到 H2 数据库
18:44:03 [SEVERE] [MultiLogin] A FATAL ERROR WAS ENCOUNTERED WHILE INITIALIZING THE PLUGIN.
java.lang.ClassCastException: class gnu.trove.map.hash.TIntObjectHashMap cannot be cast to class [Ljava.lang.Object; (gnu.trove.map.hash.TIntObjectHashMap is in unnamed module of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
    at fun.ksnb.multilogin.bungee.main.MultiLoginBungeePluginBootstrap.initService(MultiLoginBungeePluginBootstrap.java:79)
    at moe.caa.multilogin.core.main.MultiCore.init0(MultiCore.java:119)
    at moe.caa.multilogin.core.main.MultiCore.init(MultiCore.java:82)
    at fun.ksnb.multilogin.bungee.main.MultiLoginBungeePluginBootstrap.onEnable(MultiLoginBungeePluginBootstrap.java:54)
    at fun.ksnb.multilogin.bungee.loader.main.MultiLoginBungeeLoader.onEnable(MultiLoginBungeeLoader.java:35)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:294)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:113)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
18:44:03 [INFO] WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
18:44:03 [INFO] Enabled plugin MultiLogin version 0.3.13 by ksqeib, CaaMoe
```

### 描述你考虑过的备选方案

将服务端更换为Velocity，但他有缺陷，插件生态太不完善了

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [ ] 可扩展性
- [ ] 安全
- [ ] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [ ] 新的扩展
- [ ] 其他

**Comment by ksqeib445** [comment]
很抱歉 hexacord与我们进行bc分支兼容的方案出入过大 暂时不方便兼容
后续若有机会 会尝试兼容的
