### ISSUE TITLE
[Bug Report] Bungeecord 1.19 has api changes

### ISSUE THREAD

**Issue by warmbroke** [CaaMoe/MultiLogin#42]
### Bug Description

```
00:10:36 [INFO] [MultiLogin] Authentication passed, login allowed. (user: x, in game uuid: x, online uuid: x, yggdrasil: official)
00:10:36 [SEVERE] [MultiLogin] An exception occurred at the end of processing login.
java.lang.NoClassDefFoundError: net/md_5/bungee/connection/LoginResult$Property
at fun.ksnb.multilogin.bungee.impl.BungeeUserLogin.generateLoginResult(BungeeUserLogin.java:64)
at fun.ksnb.multilogin.bungee.impl.BungeeUserLogin.finish(BungeeUserLogin.java:50)
at moe.caa.multilogin.core.auth.CombineAuthCore.doAuth(CombineAuthCore.java:83)
at fun.ksnb.multilogin.bungee.auth.MultiLoginEncryptionResponse.lambda$handle$0(MultiLoginEncryptionResponse.java:67)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.connection.LoginResult$Property
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
... 10 more
```

https://github.com/CaaMoe/MultiLogin/blob/f73ddde6e96b01a17125273488e69aeeb70a50db/bungee/src/main/java/fun/ksnb/multilogin/bungee/impl/BungeeUserLogin.java#L64

Bungeecord version: CI Build 1644 https://ci.md-5.net/job/BungeeCord/1644/

### MultiLogin Version

master branch (f73ddde)

### System Architecture

linux/amd64

### Configurations

- default

### Steps to reproduce

1. Download a recent bungeecord build
2. Login with Multilogin

### Affected area

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by warmbroke** [comment]
working patch:
```
diff --git a/bungee/build.gradle b/bungee/build.gradle
index d3a2a65..65cd16e 100644
--- a/bungee/build.gradle
+++ b/bungee/build.gradle
@@ -8,7 +8,7 @@ repositories {
 }
 
 dependencies {
-    compileOnly group: 'net.md-5', name: 'bungeecord-proxy', version: '1.16-R0.5-20210527.222654-29'
+    compileOnly group: 'net.md-5', name: 'bungeecord-proxy', version: '1.19-R0.1-SNAPSHOT'
     compileOnly project(":bungee:loader")
     compileOnly project(":core:loader")
     implementation project(":core")
@@ -28,4 +28,4 @@ shadowJar {
 
 artifacts {
     archives shadowJar
-}
\ No newline at end of file
+}
diff --git a/bungee/src/main/java/fun/ksnb/multilogin/bungee/impl/BungeeUserLogin.java b/bungee/src/main/java/fun/ksnb/multilogin/bungee/impl/BungeeUserLogin.java
index 39d7f17..ee39e88 100644
--- a/bungee/src/main/java/fun/ksnb/multilogin/bungee/impl/BungeeUserLogin.java
+++ b/bungee/src/main/java/fun/ksnb/multilogin/bungee/impl/BungeeUserLogin.java
@@ -61,7 +61,7 @@ public class BungeeUserLogin extends BaseUserLogin {
 
     private LoginResult generateLoginResult(HasJoinedResponse response) {
         List<Property> values = new ArrayList<>(response.getPropertyMap().values());
-        LoginResult.Property[] properties = new LoginResult.Property[values.size()];
+        net.md_5.bungee.protocol.Property[] properties = new net.md_5.bungee.protocol.Property[values.size()];
         for (int i = 0; i < values.size(); i++) {
             properties[i] = generateProperty(values.get(i));
         }
@@ -72,7 +72,7 @@ public class BungeeUserLogin extends BaseUserLogin {
         );
     }
 
-    private LoginResult.Property generateProperty(Property property) {
-        return new LoginResult.Property(property.getName(), property.getValue(), property.getSignature());
+    private net.md_5.bungee.protocol.Property generateProperty(Property property) {
+        return new net.md_5.bungee.protocol.Property(property.getName(), property.getValue(), property.getSignature());
     }
 }
```

**Comment by CaaMoe** [comment]
Thank you for your feedback.
