### ISSUE TITLE
对于BC分支的致命错误

### ISSUE THREAD

**Issue by misss520** [CaaMoe/MultiLogin#54]
### BUG描述

无法启动，报错

### MultiLogin版本

从0.3.15往前的更多版本

### 系统架构

linux/amd64

### 配置文件

全默认

### 日志

A FATAL ERROR WAS ENCOUNTERED WHILE INITIALIZING THE PLUGIN.
>java.lang.ClassCastException: gnu.trove.map.hash.TIntObjectHashMap cannot be cast to [Ljava.lang.Object;
    at fun.ksnb.multilogin.bungee.main.MultiLoginBungeePluginBootstrap.initService(MultiLoginBungeePluginBootstrap.java:79)
    at moe.caa.multilogin.core.main.MultiCore.init0(MultiCore.java:119)
    at moe.caa.multilogin.core.main.MultiCore.init(MultiCore.java:82)
    at fun.ksnb.multilogin.bungee.main.MultiLoginBungeePluginBootstrap.onEnable(MultiLoginBungeePluginBootstrap.java:54)
    at fun.ksnb.multilogin.bungee.loader.main.MultiLoginBungeeLoader.onEnable(MultiLoginBungeeLoader.java:35)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:294)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:118)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### 复现步骤

我使用的并不是原版的BC，它是来自BC的一个分支，向下兼容了1.7X
地址:https://github.com/HexagonMC/BungeeCord/releases，使用的版本为V280
不需要进行任何操作，只要把插件丢进plugins,它就一定会报错，并且导致整个服务器关闭

### 确认一遍

- [ ] 我已完成且认真地填写完了报告所需要的信息
- [ ] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
#37
