### ISSUE TITLE
[错误报告] 无法读取配置文件？

### ISSUE THREAD

**Issue by wocw233** [CaaMoe/MultiLogin#70]
### BUG描述

java版本为 jdk-18.0.2
bc端为 waterfall-1.19-500.jar
插件为 MultiLogin-Bungee-0.5.1.jar
配置文件并未修改 仅配置了services文件夹下 三个Yggdrasil Service 配置文件

启动后插件报错无法读取文件

### MultiLogin版本

Bungee-0.5.1

### 系统架构

windows/amd64

#####################################################################
#
#     配置文件格式为 ‘YAML’，推荐使用 Visual Studio Code 浏览和编辑。
#          前往 ‘https://yaml.org/’ 查阅 YAML 配置语法
#
#           除了布尔值和整数、浮点数之外的配置，请使用引号包裹起来。
#
#    BUG REPORTS:   https://github.com/CaaMoe/MultiLogin/issues
#####################################################################

# 开启插件 DEBUG 日志。
#
# 此选项将会把插件内所有 DEBUG 日志转换成 INFO 日志。
# 默认值 false
debug: false

# 开启更新检查
#
# 插件将半天进行一次更新检查
# 默认值 true
checkUpdate: true

# 强制使用此登录
#
# 即强制使用 MultiLogin 来登录游戏。
# 默认值 true
forceUseLogin: true

# 全局禁用重名检查
#
# 默认值 false
disableDuplicateNamesCheck: false

# 插件数据设置
sql:

  # 数据库类型设置
  #
  # 请使用以下值:
  #   H2
  #   MYSQL
  # 默认值 ‘H2’
  backend: 'H2'

  # 数据库访问地址
  #
  # 默认值 ‘127.0.0.1’
  ip: 127.0.0.1

  # 端口
  #
  # 默认值 ‘3306’
  port: 3306

  # 用户名
  #
  # 默认值 ‘root’
  username: root

  # 访问密码
  #
  # 默认值 ‘root’
  password: root

  # 数据库名称
  #
  # 默认值 ‘multilogin’
  database: multilogin

  # 使用的数据表前缀。
  #
  # 使用时将会补充后缀符号 ‘_’
  # 请不要随意更改它，否则数据将消失
  # 默认值 ‘multilogin’
  tablePrefix: multilogin

  # 高级设定，指定连接 URL
  #
  # 默认值 ’‘
  connectUrl: ''

### 日志

[12:37:48 INFO] [MultiLogin]: Cover: examples/littleskin.yml
[12:37:48 INFO] [MultiLogin]: Cover: examples/offical.yml
[12:37:48 INFO] [MultiLogin]: Cover: examples/template_cn.yml
[12:37:48 ERROR] [MultiLogin]: null
moe.caa.multilogin.core.configuration.ConfException: Unable to read Yggdrasil config under file plugins\MultiLogin\services\offical.yml
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:89) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:84) ~[?:?]
        at moe.caa.multilogin.core.main.MultiCore.load(MultiCore.java:84) ~[?:?]
        at fun.ksnb.multilogin.bungee.main.MultiLoginBungee.onEnable(MultiLoginBungee.java:43) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
Caused by: moe.caa.multilogin.core.configuration.ConfException: Yggdrasil id -1 is out of bounds, The value can only be between 0 and 127.
        at moe.caa.multilogin.core.configuration.yggdrasil.YggdrasilServiceConfig.checkValid(YggdrasilServiceConfig.java:74) ~[?:?]
        at moe.caa.multilogin.core.configuration.yggdrasil.YggdrasilServiceConfig.read(YggdrasilServiceConfig.java:62) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:87) ~[?:?]
        ... 10 more
[12:37:48 ERROR] [MultiLogin]: null
moe.caa.multilogin.core.configuration.ConfException: Unable to read Yggdrasil config under file plugins\MultiLogin\services\template_cn.yml
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:89) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:84) ~[?:?]
        at moe.caa.multilogin.core.main.MultiCore.load(MultiCore.java:84) ~[?:?]
        at fun.ksnb.multilogin.bungee.main.MultiLoginBungee.onEnable(MultiLoginBungee.java:43) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
Caused by: moe.caa.multilogin.core.configuration.ConfException: There can only be one, blessingSkin, official and custom.
        at moe.caa.multilogin.core.configuration.yggdrasil.hasjoined.HasJoinedConfig.getHasJoinedConfig(HasJoinedConfig.java:33) ~[?:?]
        at moe.caa.multilogin.core.configuration.yggdrasil.YggdrasilServiceConfig.read(YggdrasilServiceConfig.java:47) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:87) ~[?:?]
        ... 10 more
[12:37:48 ERROR] [MultiLogin]: null
moe.caa.multilogin.core.configuration.ConfException: Unable to read Yggdrasil config under file plugins\MultiLogin\services\wdgm.yml
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:89) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:84) ~[?:?]
        at moe.caa.multilogin.core.main.MultiCore.load(MultiCore.java:84) ~[?:?]
        at fun.ksnb.multilogin.bungee.main.MultiLoginBungee.onEnable(MultiLoginBungee.java:43) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.19-500.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500]
Caused by: moe.caa.multilogin.core.configuration.ConfException: Yggdrasil id -1 is out of bounds, The value can only be between 0 and 127.
        at moe.caa.multilogin.core.configuration.yggdrasil.YggdrasilServiceConfig.checkValid(YggdrasilServiceConfig.java:74) ~[?:?]
        at moe.caa.multilogin.core.configuration.yggdrasil.YggdrasilServiceConfig.read(YggdrasilServiceConfig.java:62) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.lambda$reload$0(PluginConfig.java:87) ~[?:?]
        ... 10 more
[12:37:48 WARN] [MultiLogin]: The server has not added any yggdrasil service, which will prevent all players from logging in.
[12:37:49 INFO] [MultiLogin]: Loaded, using MultiLogin v0.5.1 on Waterfall - git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:42d9c68:500
[12:37:49 INFO]: Enabled plugin MultiLogin version 0.5.1 by ksqeib445, Becods, CaaMoe, ksqeib

### 复现步骤

1.
2.
3.
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
Yggdrasil id -1 is out of bounds, The value can only be between 0 and 127.

**Comment by CaaMoe** [comment]
https://github.com/CaaMoe/MultiLogin/blob/d75aa636879182057fc4fb8b7cd15dc58aa43671/core/src/main/resources/examples/template_cn.yml#L33


[Yggdrasil 服务端配置例子](https://github.com/CaaMoe/MultiLogin/wiki#yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE%E4%BE%8B%E5%AD%90)
