### ISSUE TITLE
[错误报告] 无法在 Velocity 上运行

### ISSUE THREAD

**Issue by LittleChest** [CaaMoe/MultiLogin#75]
### BUG描述

服务器中除了MultiLogin还有Geyser和Floodgate
服务端版本：Velocity #195

### MultiLogin版本

0.5.1

### 系统架构

windows/amd64

### 配置文件

```
#####################################################################
#
#     配置文件格式为 ‘YAML’，推荐使用 Visual Studio Code 浏览和编辑。
#          前往 ‘https://yaml.org/’ 查阅 YAML 配置语法
#
#           除了布尔值和整数、浮点数之外的配置，请使用引号包裹起来。
#
#    BUG REPORTS:   https://github.com/CaaMoe/MultiLogin/issues
#####################################################################

# 开启插件 DEBUG 日志。
#
# 此选项将会把插件内所有 DEBUG 日志转换成 INFO 日志。
# 默认值 false
debug: false

# 开启更新检查
#
# 插件将半天进行一次更新检查
# 默认值 true
checkUpdate: true

# 强制使用此登录
#
# 即强制使用 MultiLogin 来登录游戏。
# 默认值 true
forceUseLogin: true

# 全局禁用重名检查
#
# 默认值 false
disableDuplicateNamesCheck: false

# 插件数据设置
sql:

  # 数据库类型设置
  #
  # 请使用以下值:
  #   H2
  #   MYSQL
  # 默认值 ‘H2’
  backend: 'H2'

  # 数据库访问地址
  #
  # 默认值 ‘127.0.0.1’
  ip: 127.0.0.1

  # 端口
  #
  # 默认值 ‘3306’
  port: 3306

  # 用户名
  #
  # 默认值 ‘root’
  username: root

  # 访问密码
  #
  # 默认值 ‘root’
  password: root

  # 数据库名称
  #
  # 默认值 ‘multilogin’
  database: multilogin

  # 使用的数据表前缀。
  #
  # 使用时将会补充后缀符号 ‘_’
  # 请不要随意更改它，否则数据将消失
  # 默认值 ‘multilogin’
  tablePrefix: multilogin

  # 高级设定，指定连接 URL
  #
  # 默认值 ’‘
  connectUrl: ''
```

### 日志

```
[22:40:21] [main/INFO]: Booting up Velocity 3.1.2-SNAPSHOT (git-9cbaeb7b-b195)...
[22:40:21] [main/INFO]: Loading localizations...
[22:40:22] [main/INFO]: Connections will use NIO channels, Java compression, Java ciphers
[22:40:22] [main/INFO]: Loading plugins...
[22:40:23] [main/INFO]: 启动 Floodgate，耗时424ms
[22:40:23] [main/INFO]: Loaded plugin floodgate 2.2.0-SNAPSHOT (b73-4f36112) by GeyserMC
[22:40:23] [main/INFO]: Loaded plugin geyser 2.1.0-SNAPSHOT (git-master-247edc6) by GeyserMC
[22:40:23] [main/INFO]: Loaded plugin multilogin 0.5.1 by ksqeib445, Becods, CaaMoe, ksqeib
[22:40:24] [main/INFO]: Loaded 3 plugins
[22:40:24] [Velocity Async Event Executor - #0/WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:40:24] [Velocity Async Event Executor - #0/WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:40:25] [Velocity Async Event Executor - #0/INFO]: 正在加载插件...
[22:40:25] [Velocity Async Event Executor - #0/INFO]: 已加载 0 个插件
[22:40:25] [Velocity Async Event Executor - #0/INFO]: Cover: examples/littleskin.yml
[22:40:25] [Velocity Async Event Executor - #0/INFO]: Cover: examples/offical.yml
[22:40:25] [Velocity Async Event Executor - #0/INFO]: Cover: examples/template_cn.yml
[22:40:25] [Velocity Async Event Executor - #0/INFO]: Add a yggdrasil service with id 0 and name Unnamed.
[22:40:25] [Velocity Async Event Executor - #0/INFO]: Add a yggdrasil service with id 1 and name Unnamed.
[22:40:25] [Velocity Async Event Executor - #0/INFO]: Added 2 Yggdrasil services.
[22:40:26] [Velocity Async Event Executor - #0/INFO]: Loaded, using MultiLogin v0.5.1 on Velocity - 3.1.2-SNAPSHOT (git-9cbaeb7b-b195)
[22:40:26] [Velocity Async Event Executor - #0/ERROR]: An exception was encountered while loading the plugin.
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/chat/PlayerChat
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at moe.caa.multilogin.loader.classloader.PriorURLClassLoader.loadClass(PriorURLClassLoader.java:35) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at moe.caa.multilogin.velocity.injector.VelocityInjector.inject(VelocityInjector.java:34) ~[?:?]
	at fun.ksnb.multilogin.velocity.main.MultiLoginVelocity.onInitialize(MultiLoginVelocity.java:58) ~[?:?]
	at fun.ksnb.multilogin.velocity.main.Lmbda$5.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[Velocity.jar:3.1.2-SNAPSHOT (git-9cbaeb7b-b195)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Velocity.jar:3.1.2-SNAPSHOT (git-9cbaeb7b-b195)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Velocity.jar:3.1.2-SNAPSHOT (git-9cbaeb7b-b195)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.chat.PlayerChat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at moe.caa.multilogin.loader.classloader.PriorURLClassLoader.loadClass(PriorURLClassLoader.java:43) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 19 more
[22:40:26] [Thread-1/INFO]: Shutting down the proxy...
[22:40:26] [Velocity Async Event Executor - #1/INFO]: Geyser关闭中
[22:40:26] [Velocity Async Event Executor - #1/ERROR]: Couldn't pass ProxyShutdownEvent to geyser
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ScheduledExecutorService.shutdown()" because "this.scheduledThread" is null
	at org.geysermc.geyser.GeyserImpl.shutdown(GeyserImpl.java:544) ~[?:?]
	at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.onDisable(GeyserVelocityPlugin.java:190) ~[?:?]
	at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.onShutdown(GeyserVelocityPlugin.java:224) ~[?:?]
	at org.geysermc.geyser.platform.velocity.Lmbda$4.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[Velocity.jar:3.1.2-SNAPSHOT (git-9cbaeb7b-b195)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Velocity.jar:3.1.2-SNAPSHOT (git-9cbaeb7b-b195)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Velocity.jar:3.1.2-SNAPSHOT (git-9cbaeb7b-b195)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### 复现步骤

1. 把插件丢进去
2. 等待
3. 崩溃

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by LittleChest** [comment]
现在在用Bungee 无法继续跟踪问题

**Comment by CaaMoe** [comment]
已收到问题，正在安排修复

**Comment by CaaMoe** [comment]
https://github.com/CaaMoe/MultiLogin/actions/runs/3663611352 你可以在这次Action下获得到当前最新的Velocity能用的MultiLogin版本

**Comment by LittleChest** [comment]
> https://github.com/CaaMoe/MultiLogin/actions/runs/3663611352 你可以在这次Action下获得到当前最新的Velocity能用的MultiLogin版本
我刚才下载最新版Velocity（#198）并使用此构建，无问题
