### ISSUE TITLE
[错误报告] 无法在最新版 Velocity 上运行

### ISSUE THREAD

**Issue by MSDNicrosoft** [CaaMoe/MultiLogin#85]
#### 环境
- [最新版 Velocity (3.2.0-SNAPSHOT-216)](https://papermc.io/downloads#Velocity)
- Java 版本：17.38+21-CA (Zulu)
- `Ubuntu 22.01.1 LTS` 与 `Windows 11 22H2 - 22623.730`
- 服务端仅安装了 此插件 和 LuckPerms 插件
#### 大致过程

在启动服务端时抛出了如下日志内的异常，随后服务端关闭

#### 重要声明

这个插件是初次使用

### MultiLogin版本

0.5.2

### 系统架构

linux/amd64 与 windows/amd64

### 配置文件

与配置文件无关，第一次使用插件直接导致此问题

### 日志

```log
[Velocity Async Event Executor - #0/ERROR] [multilogin]: An exception was encountered while loading the plugin.
java.lang.IllegalAccessError: class moe.caa.multilogin.velocity.injector.VelocityInjector tried to access protected field com.velocitypowered.proxy.protocol.StateRegistry.serverbound (moe.caa.multilogin.velocity.injector.VelocityInjector is in unnamed module of loader moe.caa.multilogin.loader.classloader.PriorAllURLClassLoader @6c15e8c7; com.velocitypowered.proxy.protocol.StateRegistry is in unnamed module of loader 'app')
	at moe.caa.multilogin.velocity.injector.VelocityInjector.inject(VelocityInjector.java:32) ~[?:?]
	at fun.ksnb.multilogin.velocity.main.MultiLoginVelocity.onInitialize(MultiLoginVelocity.java:58) ~[?:?]
	at fun.ksnb.multilogin.velocity.main.Lmbda$3.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### 复现步骤

1. 将插件移入 `plugins` 文件夹
2. 启动最新版 Velocity

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
感谢反馈，问题已修复，你可以在 Action 中获得修复版本下载链接

**Comment by MSDNicrosoft** [comment]
感谢，问题已解决。
另外，请问您是否有联系方式？我想给您的仓库提点建议。
