### ISSUE TITLE
[错误报告] 无法在Velocity3.2.0(git-216)正常运行

### ISSUE THREAD

**Issue by GXLiLuoQin** [CaaMoe/MultiLogin#86]
### BUG描述

无法正常使用插件
并导致服务端无法正常启动
Velocity3.2.0(git-216)

### MultiLogin版本

0.5.3

### 系统架构

linux/amd64

#####################################################################
#
#     配置文件格式�? ‘YAML’，推荐使用 Visual Studio Code 浏览和编辑�??
#          前往 ‘https://yaml.org/�? 查阅 YAML 配置语法
#
#           除了布尔值和整数、浮点数之外的配置，请使用引号包裹起来�??
#
#    BUG REPORTS:   https://github.com/CaaMoe/MultiLogin/issues
#####################################################################

# �?启插�? DEBUG 日志�?
#
# 此�?�项将会把插件内�?�? DEBUG 日志转换�? INFO 日志�?
# 默认�? false
debug: false

# �?启更新检�?
#
# 插件将半天进行一次更新检�?
# 默认�? true
checkUpdate: true

# 强制使用此登�?
#
# 即强制使�? MultiLogin 来登录游戏�??
# 默认�? true
forceUseLogin: true

# 全局禁用重名�?�?
#
# 默认�? false
disableDuplicateNamesCheck: false

# 禁用转发�?�?
#
# 默认�? false
disableForwardingCheck: false

# 插件数据设置
sql:

  # 数据库类型设�?
  #
  # 请使用以下�??:
  #   H2
  #   MYSQL
  # 默认�? ‘H2�?
  backend: 'H2'

  # 数据库访问地�?
  #
  # 默认�? �?127.0.0.1�?
  ip: 127.0.0.1

  # 端口
  #
  # 默认�? �?3306�?
  port: 3306

  # 用户�?
  #
  # 默认�? ‘root�?
  username: root

  # 访问密码
  #
  # 默认�? ‘root�?
  password: root

  # 数据库名�?
  #
  # 默认�? ‘multilogin�?
  database: multilogin

  # 使用的数据表前缀�?
  #
  # 使用时将会补充后�?符号 ‘_�?
  # 请不要随意更改它，否则数据将消失
  # 默认�? ‘multilogin�?
  tablePrefix: multilogin

  # 高级设定，指定连�? URL
  #
  # 默认�? ’�??
  connectUrl: ''

### 日志

[14:57:12 ERROR] [multilogin]: An exception was encountered while loading the plugin.
org.spongepowered.configurate.loader.ParsingException: []: null
        at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:163) ~[?:?]
        at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:63) ~[?:?]
        at org.spongepowered.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:56) ~[?:?]
        at moe.caa.multilogin.core.configuration.PluginConfig.reload(PluginConfig.java:61) ~[?:?]
        at moe.caa.multilogin.core.main.MultiCore.load(MultiCore.java:83) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.MultiLoginVelocity.onInitialize(MultiLoginVelocity.java:56) ~[?:?]
        at fun.ksnb.multilogin.velocity.main.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[Velocity3.2.0.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Velocity3.2.0.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Velocity3.2.0.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.nio.charset.MalformedInputException: Input length = 2
        at java.nio.charset.CoderResult.throwException(CoderResult.java:274) ~[?:?]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
        at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
        at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
        at java.io.BufferedReader.read1(BufferedReader.java:213) ~[?:?]
        at java.io.BufferedReader.read(BufferedReader.java:287) ~[?:?]
        at java.io.Reader.read(Reader.java:197) ~[?:?]
        at org.spongepowered.configurate.loader.CommentHandlers.beginsWithPrefix(CommentHandlers.java:255) ~[?:?]
        at org.spongepowered.configurate.loader.CommentHandlers$AbstractPrefixHandler.extractHeader(CommentHandlers.java:204) ~[?:?]
        at org.spongepowered.configurate.loader.CommentHandlers.extractHeader(CommentHandlers.java:71) ~[?:?]
        at org.spongepowered.configurate.loader.CommentHandlers.extractComment(CommentHandlers.java:92) ~[?:?]
        at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:149) ~[?:?]

### 复现步骤

1.上传至插件文件夹
2.重新启动服务端
3.
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [ ] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by GXLiLuoQin** [comment]
已解决
