### ISSUE TITLE
[错误报告] 插件会导致 Geyser 一系列错误

### ISSUE THREAD

**Issue by wifi-left** [CaaMoe/MultiLogin#98]
### BUG描述

对于名字不符合正则表达式的，例如`wifi_left`，没装 MultiLogin前，会自动替代为 `.wifi_left`，但使用此插件后会被直接踢出。
日志：
```
wifi left 因为 您使用的名字 wifi left 与正则 ^[0-9a-zA-Z_]{3,16}$ 不匹配，请更改。 与 Java 服务器断开了连接
```
并且加上插件后基岩玩家会无法进入服务器（尝试以 Java 版玩家身份登录！Floodgate 设置正确吗？ 与 Java 服务器断开了连接）。

### 希望
希望能对使用 Floodgate 游戏的玩家先进行替换用户名，再进行正则判断。

### MultiLogin版本

v6.0.3

### 系统架构

windows/amd64

### 服务器核心

Waterfall

### 配置文件
```
debug: false
welcomeMsg: true
checkUpdate: false
forceUseLogin: true
floodgateSupport: true
nameAllowedRegular: '^[0-9a-zA-Z_. ]{3,17}$'
nameCorrect: true
```
后面省略

### 日志
关闭正则匹配后
```
13:14:42 INFO] [Geyser-BungeeCord]: wifi left 因为 尝试以 Java 版玩家身份登录！Floodgate 设置正确吗？ 与 Java 服务器断开了连接
[13:14:42 ERROR]: com.github.steveice10.mc.protocol.data.UnexpectedEncryptionException: Cannot reply to ClientboundHelloPacket without profile and access token.
[13:14:42 ERROR]:       at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:56)
[13:14:42 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.callPacketReceived(TcpSession.java:157)
[13:14:42 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:388)
[13:14:42 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:29)
[13:14:42 ERROR]:       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:14:42 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[13:14:42 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[13:14:42 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:14:42 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[13:14:42 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[13:14:42 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:14:42 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:14:42 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[13:14:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:14:42 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[13:14:42 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[13:14:42 ERROR]:       at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[13:14:42 ERROR]:       at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[13:14:42 ERROR]:       at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[13:14:42 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[13:14:42 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[13:14:42 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[13:14:42 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:14:42 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[13:14:42 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

### 复现步骤

在配置文件已启用 Floodgate 支持

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
感谢反馈，最新的提交已修复了这个问题
